### PR TITLE
Feature/quick settings custom element

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by fundon** [comment]
I had make a post on Atom'discuss.
https://discuss.atom.io/t/minimap-new-feature-tester-needed/14919

**Comment by fundon** [comment]
@abe33 see https://github.com/fundon/atom-minimap/blob/feature/quick_settings_custom_element/lib/minimap-element.coffee#L279

```coffee
    @applyStyles @controls,
      width: Math.min(@canvas.width, @width) + 'px'
```

The codes should replace with:

```coffee
    @applyStyles @controls,
      width: Math.min(@canvas.width / devicePixelRatio, @width) + 'px'
```

If the `window.devicePixelRatio` is not `1`, the `canvas.width` will be x2 (window.devicePixelRatio = 2) https://github.com/fundon/atom-minimap/blob/feature/quick_settings_custom_element/lib/minimap-element.coffee#L345, but the `controls` div does not need x2 width.

I think that this issue' point.

**Comment by abe33** [comment]
The `devicePixelRatio` is much more legit than the previous solution. I'll see how I can cover retina screen in some tests. There's probably a need for some helpers method to doesn't have to multiply/divide the width explicitely every time we make a computation.

**Comment by fundon** [comment]
Yep, detects `devicePixelRatio` is needful.

**Comment by fundon** [comment]
I added `minimap.devicePixelRatio` setting for high-DPI device.
Now, everything looks good.

**Comment by fundon** [comment]
Ok, I removed the setting.
I'm not sure that we need it.

**Comment by fundon** [comment]
Yeah, it's released! :+1:

**Pull request merged**
