### PR TITLE
Add scroll animation.

### PR DESCRIPTION
**Pull request by xndcn**
Hi, I just add scroll animation by using jQuery.animate, and leave it disabled by default. I wish you will like it, thanks.

### CODE REVIEW

**Comment by abe33** [comment]
Thanks for implementing this feature, I think it have been on the todo for months now. 

However, I would prefer an implementation that doesn't rely on jQuery if possible, the main change in v4 was to get rid of `space-pen` views for the minimap, and I plan to make the same changes for the quick settings view soon. Do you mind modifying the PR so that the `MinimapElement` doesn't rely on `jQuery`?

**Comment by xndcn** [comment]
@abe33 OK, I will try it.

**Comment by xndcn** [comment]
@abe33 How about this one? I just use a handmade `animate` function by using `requestAnimationFrame`.
I'm not sure why CI test failed. It works for me.

**Comment by fundon** [comment]
Which is version of your Atom?

**Comment by xndcn** [comment]
@fundon Sorry, I made a mistake, fix soon...

**Comment by fundon** [comment]
@xndcn I tested locally it. It's working. :+1:

**Comment by abe33** [comment]
@xndcn Yeah a handmade method is great :)

Also, if you could add basic tests for the setting so that we don't break it in the future would be great :)

For the CI build I'm on it, I think there's some issue with the events flow on Travis when changing settings.

**Comment by xndcn** [comment]
@abe33 OK, test spec has added :)

**Comment by fundon** [comment]
Nice!

**Comment by abe33** [comment]
Released in 4.1.0

**Pull request merged**
